server:
    port : 8089
logging:
    config: classpath:logback.xml
spring:
    profiles:
        active: subscribeinfo
    datasource:
      url: jdbc:mysql://123.56.96.252:3306/restaurant?useUnicode=true&characterEncoding=UTF-8&rewriteBatchedStatements=true&serverTimezone=UTC&useSSL=false
      username: restaurantsys
      password: Restaurant123456@
      driver-class-name: com.mysql.jdbc.Driver

read:
   fist-line: 1
import:
   once-size: 2000
subscrinfo:
    perview:
        dir: D:\\亚信\\天津电信\\test\\
        file: SUBSCRIBERRENTINFO.xlsx
        read: 1
    monthpack:
        dir: D:\\亚信\\天津电信\\test\\
        file: SERORDERINFO.xlsx
        read: 1

